services:
  - type: web
    name: baby-frontend
    runtime: python
    buildCommand: ""
    startCommand: streamlit run frontend/streamlit_app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PORT
        value: 8000
